name: .NET Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore InventoryVenturus.sln

    - name: Build solution
      run: dotnet build InventoryVenturus.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test InventoryVenturus.Tests/InventoryVenturus.Tests.csproj --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --collect:"XPlat Code Coverage"

    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'

    - name: Publish code coverage
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: '**/coverage.cobertura.xml'
        
    - name: Report Unit Tests
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx

    - name: Generate code coverage report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

    - name: Publish code coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage-report
